/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author antonio
 */
public class mdiSanRamon extends javax.swing.JFrame {

    /**
     * Creates new form mdiSanRamon
     */
    public mdiSanRamon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemUsuarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemProveedores = new javax.swing.JMenuItem();
        itemRecetas = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        itemVales = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemProductos = new javax.swing.JMenuItem();
        itemMedidas = new javax.swing.JMenuItem();
        itemEntradas = new javax.swing.JMenuItem();
        itemSalidas = new javax.swing.JMenuItem();
        itemLotes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unidad de salud San Ramón");
        setPreferredSize(new java.awt.Dimension(900, 700));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Administrar");

        itemUsuarios.setMnemonic('o');
        itemUsuarios.setText("Usuarios");
        itemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuariosActionPerformed(evt);
            }
        });
        fileMenu.add(itemUsuarios);

        menuBar.add(fileMenu);

        jMenu1.setText("Transacciones");

        itemProveedores.setText("Proveedores");
        itemProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedoresActionPerformed(evt);
            }
        });
        jMenu1.add(itemProveedores);

        itemRecetas.setText("Destinatarios");
        itemRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRecetasActionPerformed(evt);
            }
        });
        jMenu1.add(itemRecetas);

        jMenuItem3.setText("Recetas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        itemVales.setText("Vales");
        itemVales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemValesActionPerformed(evt);
            }
        });
        jMenu1.add(itemVales);

        menuBar.add(jMenu1);

        jMenu2.setText("Inventario");

        itemProductos.setText("Productos");
        itemProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductosActionPerformed(evt);
            }
        });
        jMenu2.add(itemProductos);

        itemMedidas.setText("Medidas");
        itemMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMedidasActionPerformed(evt);
            }
        });
        jMenu2.add(itemMedidas);

        itemEntradas.setText("Entradas");
        itemEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEntradasActionPerformed(evt);
            }
        });
        jMenu2.add(itemEntradas);

        itemSalidas.setText("Salidas");
        itemSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalidasActionPerformed(evt);
            }
        });
        jMenu2.add(itemSalidas);

        itemLotes.setText("Lotes");
        itemLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLotesActionPerformed(evt);
            }
        });
        jMenu2.add(itemLotes);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuariosActionPerformed
        if(UsuarioMantenimiento.bandera==0)
        {
            UsuarioMantenimiento mantenimientoUsuario = new UsuarioMantenimiento();
            desktopPane.add(mantenimientoUsuario);
            mantenimientoUsuario.show();
            UsuarioMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemUsuariosActionPerformed

    private void itemProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedoresActionPerformed
        if(ProveedorMantenimiento.bandera == 0)
        {
            ProveedorMantenimiento mantenimientoProveedor = new ProveedorMantenimiento();
            desktopPane.add(mantenimientoProveedor);
            mantenimientoProveedor.show();
            ProveedorMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemProveedoresActionPerformed

    private void itemRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecetasActionPerformed
        if(DestinatarioMantenimiento.bandera==0)
        {
            DestinatarioMantenimiento mantenimientoDestinatario = new DestinatarioMantenimiento();
            desktopPane.add(mantenimientoDestinatario);
            mantenimientoDestinatario.show();
            DestinatarioMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemRecetasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(RecetaMantenimiento.bandera==0)
        {
            RecetaMantenimiento mantenimientoReceta = new RecetaMantenimiento();
            desktopPane.add(mantenimientoReceta);
            mantenimientoReceta.show();
            RecetaMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void itemValesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemValesActionPerformed
        if(ValeMantenimiento.bandera==0)
        {
            ValeMantenimiento mantenimientoVale = new ValeMantenimiento();
            desktopPane.add(mantenimientoVale);
            mantenimientoVale.show();
            ValeMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemValesActionPerformed

    private void itemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductosActionPerformed
        if(ProductoMantenimiento.bandera==0)
        {
            ProductoMantenimiento mantenimientoProducto = new ProductoMantenimiento();
            desktopPane.add(mantenimientoProducto);
            mantenimientoProducto.show();
            ProductoMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemProductosActionPerformed

    private void itemMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMedidasActionPerformed
        if(UnidadMedidaMantenimiento.bandera==0)
        {
            UnidadMedidaMantenimiento mantenimientoMedida = new UnidadMedidaMantenimiento();
            desktopPane.add(mantenimientoMedida);
            mantenimientoMedida.show();
            UnidadMedidaMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemMedidasActionPerformed

    private void itemEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEntradasActionPerformed
        if(EntradaMantenimiento.bandera==0)
        {
            EntradaMantenimiento mantenimientoEntrada = new EntradaMantenimiento();
            desktopPane.add(mantenimientoEntrada);
            mantenimientoEntrada.show();
            EntradaMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemEntradasActionPerformed

    private void itemSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalidasActionPerformed
        if(SalidaMantenimiento.bandera==0)
        {
            SalidaMantenimiento mantenimientoSalida = new SalidaMantenimiento();
            desktopPane.add(mantenimientoSalida);
            mantenimientoSalida.show();
            SalidaMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemSalidasActionPerformed

    private void itemLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLotesActionPerformed
        if(LoteMantenimiento.bandera==0)
        {
            LoteMantenimiento mantenimientoLote = new LoteMantenimiento();
            desktopPane.add(mantenimientoLote);
            mantenimientoLote.show();
            LoteMantenimiento.bandera=1;
        }
    }//GEN-LAST:event_itemLotesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiSanRamon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiSanRamon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiSanRamon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiSanRamon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiSanRamon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemEntradas;
    private javax.swing.JMenuItem itemLotes;
    private javax.swing.JMenuItem itemMedidas;
    private javax.swing.JMenuItem itemProductos;
    private javax.swing.JMenuItem itemProveedores;
    private javax.swing.JMenuItem itemRecetas;
    private javax.swing.JMenuItem itemSalidas;
    private javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JMenuItem itemVales;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
