/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.org.apache.bcel.internal.generic.SALOAD;
import controller.productoController;
import entity.ProductoBean;
import entity.RecetaBean;
import entity.SalidaBean;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ProductoModel;
import model.RecetaModel;
import model.SalidaModel;

/**
 *
 * @author antonio
 */
public class RecetaMantenimiento extends javax.swing.JInternalFrame {
    productoController controladorProducto = new productoController();
    ProductoBean objeProducto;
    RecetaBean objeReceta;
    List<SalidaBean> listaSalidas = new ArrayList<SalidaBean>();

    /**
     * Creates new form RecetaMantenimiento
     */
    
    static int bandera=0;
    
    public RecetaMantenimiento() throws SQLException{
        initComponents();
        tblTodosProductos.setModel(controladorProducto.cargarTabla().getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTodosProductos = new javax.swing.JTable();
        btnCrearReceta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReceta = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnEntregarReceta = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Recetas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Código");

        tblTodosProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Descripción", "Nivel de Uso", "Unidad de Medida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTodosProductos.setEnabled(false);
        tblTodosProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTodosProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTodosProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTodosProductos);
        if (tblTodosProductos.getColumnModel().getColumnCount() > 0) {
            tblTodosProductos.getColumnModel().getColumn(0).setResizable(false);
            tblTodosProductos.getColumnModel().getColumn(1).setResizable(false);
            tblTodosProductos.getColumnModel().getColumn(2).setResizable(false);
            tblTodosProductos.getColumnModel().getColumn(3).setResizable(false);
            tblTodosProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnCrearReceta.setText("Iniciar Entrega");
        btnCrearReceta.setRequestFocusEnabled(false);
        btnCrearReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRecetaActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione el producto a entregar");

        jLabel3.setText("Cantidad");

        txtCantidad.setEnabled(false);

        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReceta.setEnabled(false);
        jScrollPane2.setViewportView(tblReceta);
        if (tblReceta.getColumnModel().getColumnCount() > 0) {
            tblReceta.getColumnModel().getColumn(0).setResizable(false);
            tblReceta.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel4.setText("Productos de la receta");

        btnEntregarReceta.setText("Finalizar y Entregar");
        btnEntregarReceta.setEnabled(false);
        btnEntregarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarRecetaActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 151, Short.MAX_VALUE)
                        .addComponent(btnCrearReceta))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReiniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEntregarReceta)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearReceta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntregarReceta)
                    .addComponent(btnReiniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        RecetaMantenimiento.bandera=0;
    }//GEN-LAST:event_formInternalFrameClosing

    private void tblTodosProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTodosProductosMouseClicked
        // TODO add your handling code here:
        if(tblTodosProductos.getSelectedRow()>=0)
        {
            try
            {
                int id= Integer.valueOf(tblTodosProductos.getModel().getValueAt(tblTodosProductos.getSelectedRow(), 0).toString());
                objeProducto = new ProductoModel().getProductoBeanById(id);
                txtCantidad.setEnabled(true);
                btnAgregar.setEnabled(true);
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(this, "¡Ocurrió un error! " + ex.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_tblTodosProductosMouseClicked

    
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try
        {
            float cantidad = Float.parseFloat(txtCantidad.getText());
            SalidaBean objeSalida = new SalidaBean();
            objeSalida.setId_producto(objeProducto);
            objeSalida.setCantidadSalida(Float.parseFloat(txtCantidad.getText()));
            objeSalida.setTipoSalida(1);
            objeSalida.setId_receta(objeReceta);
            objeSalida.setId_vale(null);
            listaSalidas.add(objeSalida);
            txtCantidad.setEnabled(false);
            btnAgregar.setEnabled(false);
            txtCantidad.setText(null);
            recargarTabla();
        }
        catch(Exception err)
        {
            JOptionPane.showMessageDialog(this, "Valor no válido");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    
    private void btnCrearRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRecetaActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Campo vacío");
        }
        else
        try
        {
            objeReceta= new RecetaBean();
            objeReceta.setFechaEntrega(new Date());
            objeReceta.setCodigoReceta(txtCodigo.getText());
            new RecetaModel().newReceta(objeReceta);
            objeReceta = new RecetaModel().getLastReceta();
            
            //Habilitando y deshabilitando
            txtCodigo.setEnabled(false);
            btnCrearReceta.setEnabled(false);
            
            tblReceta.setEnabled(true);
            tblTodosProductos.setEnabled(true);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "Error");
        }
        
    }//GEN-LAST:event_btnCrearRecetaActionPerformed

    private void btnEntregarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarRecetaActionPerformed
        // TODO add your handling code here:
        try
        {
            for(SalidaBean objeto : listaSalidas)
            {
                JOptionPane.showMessageDialog(this, objeto.getId_producto().getNombreProducto());
                new SalidaModel().newSalida(objeto);
                btnEntregarReceta.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Receta entregada exitosamente");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error" + ex.getMessage());
        }
    }//GEN-LAST:event_btnEntregarRecetaActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        controladorProducto = new productoController();
        objeProducto = null;
        objeReceta=null;
        List<SalidaBean> listaSalidas = new ArrayList<SalidaBean>();
        txtCodigo.setEnabled(true);
        btnCrearReceta.setEnabled(true);
        tblReceta.setEnabled(false);
        tblTodosProductos.setEnabled(false);
        txtCantidad.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnEntregarReceta.setEnabled(false);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    void recargarTabla()
    {
        tblReceta.removeAll();
        DefaultTableModel model = (DefaultTableModel) tblReceta.getModel();
        model.setRowCount(0);
        for(SalidaBean objeto : listaSalidas)
        {
            model.addRow(new Object[]{objeto.getId_producto().getNombreProducto(),objeto.getCantidadSalida()});
        }
        btnEntregarReceta.setEnabled(listaSalidas.size()!=0);
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCrearReceta;
    private javax.swing.JButton btnEntregarReceta;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReceta;
    private javax.swing.JTable tblTodosProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
